from pathlib import Path
p=Path('services/management_service.py')
s=p.read_text(encoding='utf-8')
old='''        CREATE UNIQUE INDEX IF NOT EXISTS ux_products_company_code\n            ON Products (CompanyID, ProductCode);\n\n        CREATE UNIQUE INDEX IF NOT EXISTS ux_product_bom_product\n            ON ProductBOM (ProductID);\n\n        CREATE UNIQUE INDEX IF NOT EXISTS ux_contracts_company_code\n            ON Contracts (CompanyID, ContractCode);\n\n        CREATE UNIQUE INDEX IF NOT EXISTS ux_contract_products_pair\n            ON ContractProducts (ContractID, ProductID);\n'''
s=s.replace(old,'')
old2='''        conn.execute("""\n            INSERT INTO Products (CompanyID, ProductCode, ProductName, Unit)\n            VALUES (?, ?, ?, ?)\n            ON CONFLICT(CompanyID, ProductCode) DO UPDATE SET\n                ProductName=excluded.ProductName,\n                Unit=CASE WHEN excluded.Unit<>'' THEN excluded.Unit ELSE Products.Unit END\n        """, (company_id, code, name, unit))\n        row = conn.execute(\n            "SELECT ProductID FROM Products WHERE CompanyID=? AND ProductCode=?",\n            (company_id, code),\n        ).fetchone()\n        product_id = int(row["ProductID"])\n        conn.execute("""\n            INSERT INTO ProductBOM (ProductID, CostPerKg, CostPerMeter, Notes, UpdatedAt)\n            VALUES (?, ?, ?, ?, datetime('now','localtime'))\n            ON CONFLICT(ProductID) DO UPDATE SET\n                CostPerKg=excluded.CostPerKg,\n                CostPerMeter=excluded.CostPerMeter,\n                Notes=excluded.Notes,\n                UpdatedAt=excluded.UpdatedAt\n        """, (product_id, kg, meter, str(payload.get("notes", "")).strip()))\n'''
new2='''        row = conn.execute(\n            "SELECT ProductID FROM Products WHERE CompanyID=? AND ProductCode=? ORDER BY ProductID LIMIT 1",\n            (company_id, code),\n        ).fetchone()\n        if row is None:\n            cursor = conn.execute("""\n                INSERT INTO Products (CompanyID, ProductCode, ProductName, Unit)\n                VALUES (?, ?, ?, ?)\n            """, (company_id, code, name, unit))\n            product_id = int(cursor.lastrowid)\n        else:\n            product_id = int(row["ProductID"])\n            conn.execute("""\n                UPDATE Products\n                   SET ProductName=?,\n                       Unit=CASE WHEN ?<>'' THEN ? ELSE Unit END\n                 WHERE ProductID=?\n            """, (name, unit, unit, product_id))\n\n        bom = conn.execute(\n            "SELECT BOMID FROM ProductBOM WHERE ProductID=? ORDER BY BOMID LIMIT 1",\n            (product_id,),\n        ).fetchone()\n        notes = str(payload.get("notes", "")).strip()\n        if bom is None:\n            conn.execute("""\n                INSERT INTO ProductBOM\n                    (ProductID, CostPerKg, CostPerMeter, Notes, UpdatedAt)\n                VALUES (?, ?, ?, ?, datetime('now','localtime'))\n            """, (product_id, kg, meter, notes))\n        else:\n            conn.execute("""\n                UPDATE ProductBOM\n                   SET CostPerKg=?,\n                       CostPerMeter=?,\n                       Notes=?,\n                       UpdatedAt=datetime('now','localtime')\n                 WHERE BOMID=?\n            """, (kg, meter, notes, int(bom["BOMID"])))\n'''
if old2 not in s: raise SystemExit('save_product block not found')
s=s.replace(old2,new2,1)
old3='''            conn.execute("""\n                INSERT INTO Products (CompanyID, ProductCode, ProductName, Unit)\n                VALUES (?, ?, ?, ?)\n                ON CONFLICT(CompanyID, ProductCode) DO UPDATE SET\n                    ProductName=excluded.ProductName,\n                    Unit=CASE WHEN excluded.Unit<>'' THEN excluded.Unit ELSE Products.Unit END\n            """, (company_id, pcode, pname, unit))\n            product = conn.execute(\n                "SELECT ProductID FROM Products WHERE CompanyID=? AND ProductCode=?",\n                (company_id, pcode),\n            ).fetchone()\n'''
new3='''            product = conn.execute(\n                "SELECT ProductID FROM Products WHERE CompanyID=? AND ProductCode=? ORDER BY ProductID LIMIT 1",\n                (company_id, pcode),\n            ).fetchone()\n            if product is None:\n                cursor = conn.execute("""\n                    INSERT INTO Products (CompanyID, ProductCode, ProductName, Unit)\n                    VALUES (?, ?, ?, ?)\n                """, (company_id, pcode, pname, unit))\n                product = conn.execute(\n                    "SELECT ProductID FROM Products WHERE ProductID=?",\n                    (cursor.lastrowid,),\n                ).fetchone()\n            else:\n                conn.execute("""\n                    UPDATE Products\n                       SET ProductName=?,\n                           Unit=CASE WHEN ?<>'' THEN ? ELSE Unit END\n                     WHERE ProductID=?\n                """, (pname, unit, unit, int(product["ProductID"])))\n'''
if old3 not in s: raise SystemExit('save_contract product block not found')
s=s.replace(old3,new3,1)
# Remove the temporary workflow files after patching is applied through this script.
# They are not required at runtime and would otherwise keep producing failed runs.
s=s
p.write_text(s,encoding='utf-8')
